# Generated by Django 3.2.1 on 2023-05-03 08:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_matiere', models.CharField(choices=[('Accessoires', 'Accessoires'), ('Matiere premiere Electronique', 'Matière première Électronique'), ('Matiere premiere Mecanique', 'Matière première Mécanique')], max_length=30)),
                ('numero_rc', models.CharField(max_length=20)),
                ('numero_nif', models.CharField(max_length=20)),
                ('numero_nis', models.CharField(max_length=20)),
                ('numero_telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Velo', 'Vélo'), ('e-velo', 'Vélo électrique'), ('e-scotter', 'Scooter électrique'), ('Accessoires', 'Accessoires'), ('Matiere 1 ere', 'matiere 1 ere')], max_length=30, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='produits_images/photo_non_dispo.png', upload_to='produits_images/')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('source', models.CharField(choices=[('Startup', 'Produit fabriqué par la startup'), ('Fournisseur', "Produit acheté auprès d'un fournisseur")], default='Startup', max_length=30)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_app.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitVendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('meca', 'Mecanique'), ('elec', 'Electronique'), ('Assemblage', 'Assemblage'), ('Gerant', 'Gestion'), ('Agent_showroom', 'Showroom'), ('stock', 'Gestion de stock')], max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.client')),
                ('produits', models.ManyToManyField(through='erp_app.ProduitVendu', to='erp_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='produitvendu',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.vente'),
        ),
    ]
