# Generated by Django 4.2.1 on 2023-05-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture_showroom',
            name='panier',
            field=models.ManyToManyField(null=True, to='erp_app.panier'),
        ),
        migrations.AlterField(
            model_name='facture_showroom',
            name='total_panier',
            field=models.FloatField(default=0, null=True),
        ),
    ]
