# Generated by Django 4.2.1 on 2023-05-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_alter_facture_showroom_panier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture_showroom',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='facture_showroom',
            name='total_panier',
        ),
        migrations.AlterField(
            model_name='facture_showroom',
            name='Reduction',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
