# Generated by Django 4.2.1 on 2023-05-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
