# Generated by Django 4.2.1 on 2023-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_remove_facture_showroom_panier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_showroom',
            name='paniers',
            field=models.ManyToManyField(to='erp_app.panier'),
        ),
    ]
