# Generated by Django 4.2.1 on 2023-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0004_facture_showroom_paniers'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_showroom',
            name='Total_price',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture_showroom',
            name='paniers',
            field=models.ManyToManyField(blank=True, to='erp_app.panier'),
        ),
    ]
