# Generated by Django 4.2.1 on 2023-05-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0005_facture_showroom_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture_showroom',
            name='paniers',
        ),
    ]
