# Generated by Django 4.2.1 on 2023-05-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0005_rename_timestamp_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rec_id',
            field=models.IntegerField(default=0),
        ),
    ]
