# Generated by Django 4.2.1 on 2023-05-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0006_notification_rec_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='rec_id',
        ),
    ]
