# Generated by Django 4.2.1 on 2023-05-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0006_remove_facture_showroom_paniers'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_showroom',
            name='paniers',
            field=models.ManyToManyField(blank=True, to='erp_app.panier'),
        ),
    ]
