# Generated by Django 4.2.1 on 2023-05-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0007_facture_showroom_paniers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture_showroom',
            name='paniers',
        ),
    ]
