# Generated by Django 4.2.1 on 2023-05-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0007_remove_notification_rec_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
