# Generated by Django 4.2.1 on 2023-05-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0008_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
    ]
