# Generated by Django 4.2.1 on 2023-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0008_remove_facture_showroom_paniers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture_showroom',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10, null=True),
        ),
    ]
