# Generated by Django 4.2.1 on 2023-05-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0009_alter_facture_showroom_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_showroom',
            name='Total_p',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10, null=True),
        ),
    ]
