# Generated by Django 4.2.1 on 2023-05-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0009_remove_notification_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
