# Generated by Django 4.2.1 on 2023-05-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0011_notification_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
