# Generated by Django 4.2.1 on 2023-05-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0014_remove_notification_recipient_usernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
