# Generated by Django 4.2.1 on 2023-05-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0017_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Pending', max_length=100),
        ),
    ]
