# Generated by Django 3.2.19 on 2023-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0020_order_shipping_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='tracking_number',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
