# Generated by Django 3.2.19 on 2023-05-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0021_auto_20230524_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='send_notification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
